README.md

Programming the ESP32 with Nim.
Reorder Embedded section alphabetically.

Add elcritch/nesper to embedded

---

README.md

Add clapfn to argument parsers

---

README.md

Add nodejs package

---

README.md

Add Cliche

---

README.md

Also, maybe we should remove/somehow indicate abandoned packages or similar? E.g. nimterop isn't really maintained anymore.

Add Futhark

---

README.md

- Added Computer Programming with Nim to the book section
- Moved Nim Memory and Nim ARC to the Websites section
- Moved dev.to to the Blogs section
- Consistent capitalization

Restructure Resources section

---

README.md

This wrapper has examples and we are using it to build our own game. :)

Added Norx game engine wrapper

---

README.md

[Rendered](https://github.com/j-james/awesome-nim#--)
This PR reorganizes the document by lumping related sections together under new (or existing) headings. 
Let me know if you like (or dislike) this reordering, and if there's anything you'd like me to change! 
If it looks good, I also have some additions from the Curated Nim packages wiki. Otherwise I can rebase those on the original structure.
The full list of changes are below:
<details>
<summary>Expand</summary>
Create a new Language Features header, nesting:
- Implementations, Standard Libraries, Package Repositories, Async IO, Threading, and Macros
Create a new Operating System header, nesting:
- System API, IO, Date and Time, Randomization, and Scripting
Move Embedded under the Hardware header
Create a new Data header, nesting:
- …

Reorganize package list

---

README.md

[Rendered](https://github.com/j-james/awesome-nim#--)
This PR:
- Adds some packages from the Curated Packages wiki list
- Adds error handling, contracts, object-oriented programming, and iteration sections
- Splits up the GUI and game development sections

Assorted updates

---

README.md

* Rearranging of some projects by stargazer count
* Updates to descriptions of some projects
* Changes link to Nim in Action book's official site

Various misc improvements

---

README.md

Rapid and nodesnim has been archived.

Removed archived game dev resources.

---

README.md

This pipe library offers more, than the already listed https://github.com/5paceToast/pipe

Add nim-pipexp

---

README.md

I do think it fits more here. I also find pattern matching to be a much broader feature, as to just put it under the category "Text" https://github.com/ringabout/awesome-nim#text
Does pattern matching fulfill no need, other than dealing with text? Some programming languages do their control flow entirely with pattern matching.

Move shell to processes

---

README.md

Example projects to kick-start Nintendo Switch Homebrew Nim Development
I'd like to have projects like these on the list so I can dive right in the switch development.

Add: nimNx and nimNxStatic

---

README.md

fixes #44; added Binarylang and Moe

---

README.md

For compliance with https://github.com/sindresorhus/awesome/pull/2442#issuecomment-1330413628

fixes #45; Added footnotes

---

README.md

Added the @benob's Gemini library, Gemini Servers group and Nemini, a Gemini Server

Added Gemini Protocol and Gemini Servers

---

README.md

Hi there
Hope it is okay to add an entry, a my little game engine written in Nim. Not production ready but working examples and tests, with a clear roadmap and weekly new features.

Added semicongine

---

README.md

`akane` is outdated. Replaced with `happyx`.

Add `happyx` 🎈

---

README.md

Yahttp - HTML client that based on Nim std/httpclient, has no additional dependencies and has nice (at least I think so) API
https://github.com/mishankov/yahttp

Add yahttp

---

README.md

Hi, I would like to contribute with these packages. 👋

Add `Cmdos`, `tinyre` and `HexToAnsi`

---

README.md

Added `norg` backup wrapper and `threadlogging`

Add norg and threadlogging

---

README.md

Adding nim-palladian to the README

Update README.md for nim-palladian

---

README.md

Added saohime and alasgar game engines under `Game Engines`

Added saohime and alasgar game engines

---

README.md

Updated README.md with high-performance library targeting lattice field theory calculations. Library is used by numerous researchers in lattice field theory, along with the Lattice Strong Dynamics collaboration.

Update "science" section of README.md

---

README.md

This one's a real hidden Gem, by GULPF of Nimquery fame

add tiny_sqlite

---

README.md

iniplus is an INI parser whose primary feature is that it supports arrays, tables and it has intuitive writing support.
I believe it meets the criteria given that it is tested, has online documentation, is stable and actively-maintained (Although there haven't been features to add or bugs to fix in the past 3 months or so)
This PR also re-sorts the packages in the "Parsing" category.

Add iniplus

---

README.md

Add kuzu, sort database driver section.

---

README.md

Another addition and more sorting.

Add tnetstring, sort serialization section.

---

README.md

Updated the Terminal section to include several new tools.
Also, updated to fix [Issue #70 - Remove NimCx](https://github.com/ringabout/awesome-nim/issues/70) since there isn't a main repo for NimCx. Nimble can't download it either. The only repo containing the project (as reported in the issue) has not been touched in 8 years as of this pull request.

Update Terminal section

---

README.md

Added SQL drivers [surrealdb.nim](https://github.com/Xkonti/surrealdb.nim) and [db_connector](https://github.com/nim-lang/db_connector) to the driver section.

Add SQL Drivers to Driver Section
